name: Developer_branch_CI
on: [workflow_call]

jobs:
  CI_Steps:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Unit Tests
        run: echo Unit Tests

      - name: Integration Tests
        run: echo Integration Tests

      - name: Code Quality
        run: echo Code Quality



