name: Developer_branch_CI
on: [workflow_call]

jobs:
  CI_Steps:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Unit Tests
        run: echo Unit Tests

      - name: Integration Tests
        run: echo Integration Tests

      - name: Code Quality
        run: sonar-scanner -Dsonar.host.url=http://sonarqube-int.tsdevops25.online:9000 -Dsonar.login=$SONAR_USER -Dsonar.password=$SONAR_PASS -Dsonar.projectKey=expense-backend
        env:
          SONAR_USER: ${{ secrets.SONAR_USER }}
          SONAR_PASS: ${{ secrets.SONAR_PASS }}




